
services:
  api:
    build:
      context: api
    environment:
      - STITCH_API_KEY=${STITCH_API_KEY:-abc123}
      - STITCH_API_PORT=${STITCH_API_PORT:-8000}
      - STITCH_API_LOG_LEVEL=${STITCH_API_LOG_LEVEL:-info}
      - STITCH_DB_PORT=${STITCH_DB_PORT:-5432}
      - PYTHONUNBUFFERED=1
    ports:
      - "${STITCH_API_PORT:-8000}:${STITCH_API_PORT:-8000}"
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc
      STITCH_DB_PORT: ${STITCH_DB_PORT:-5432}
    ports:
      - "${STITCH_DB_PORT:-5432}:${STITCH_DB_PORT:-5432}"
    command: -p ${STITCH_DB_PORT:-5432}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
